apiVersion: v1
kind: Service
metadata:
  name: ml-model-service
  labels:
    app: ml-model
spec:
  type: LoadBalancer
  selector:
    app: ml-model
  ports:
    - protocol: TCP
      port: 8080        # external port
      targetPort: 5001 # container port
